In [1]:
import numpy as np
from stencilpal.math_utils import polynomial_evaluate

In [2]:
p1 = np.polynomial.Polynomial([0, 1, 2, 0, 0, 0, 0, 0, 1])
p2 = np.array([1, 0, 0, 0, 0, 0, 2, 1, 0])

In [3]:
%%timeit
p1(1)

5.8 μs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
%%timeit
polynomial_evaluate(p2, 1)

10.2 μs ± 236 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
np.mean(np.array([1, 9]))

5.0

In [7]:
np.empty_like(np.array([0, 1, 2, 3, 4]))

array([                  0, 4602678819172646912, 4607182418800017408,
       4609434218613702656, 4611686018427387904])

In [9]:
np.array([0, 1]) * np.array([1.0, 2.0])

array([0., 2.])

In [17]:
p = 4
np.arange(-(-2 * (-p // 2)), -2 * (-p // 2) + 2, 2)

array([-4, -2,  0,  2,  4])

In [18]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 1, 2, 3, 4])

In [20]:
x[2], y[2] = 1, 1
x, y

(array([0, 1, 1, 3, 4]), array([0, 1, 1, 3, 4]))

In [21]:
np.append(1, np.array([2, 3, 4, 5]))

array([1, 2, 3, 4, 5])