In [1]:
import numpy as np
from stencilpal import (
    compute_conservative_interpolation_stencil_weights,
    conservative_interpolation_stencil,
)

In [2]:
p = 0
np.arange(-(-2 * (-p // 2)), -2 * (-p // 2) + 2, 2)

array([0])

In [3]:
w = compute_conservative_interpolation_stencil_weights(
    np.array([-6, -4, -2, 0, 2, 4, 6]), 1
)
w, np.sum(w)

(array([  -3,   25, -101,  319,  214,  -38,    4]), 420)

In [4]:
%%time
conservative_interpolation_stencil(5, 1)

CPU times: user 2.74 ms, sys: 1.52 ms, total: 4.26 ms
Wall time: 2.92 ms


array([ -1,   8, -31,  94,  59, -10,   1])